# Generated by Django 2.2.2 on 2019-06-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('ip_por', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_por', models.CharField(max_length=70)),
                ('titular_p', models.CharField(max_length=130)),
                ('descripcion_por', models.CharField(max_length=500)),
                ('imagen_por', models.CharField(max_length=100)),
                ('lugar_por', models.CharField(max_length=100)),
                ('fecha_por', models.CharField(max_length=60)),
                ('calificacion_por', models.IntegerField()),
            ],
            options={
                'db_table': 'portafolio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_pro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pro', models.CharField(max_length=60)),
                ('titular_pro', models.CharField(max_length=100)),
                ('descripcion_pro', models.CharField(max_length=300)),
                ('imagen_pro', models.CharField(max_length=100)),
                ('precio_pro', models.FloatField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
